ROUTE_POST_STATIC_BATCHING_COMPLETION = "/completion/v1"
ROUTE_POST_CONTINUOUS_BATCHING_COMPLETION = "/completion/v2"
ROUTE_POST_OPENAI_CHAT_COMPLETION = "/chat_completion/v1"
ROUTE_GET_MODEL_ID = "/model_id"

ROUTE_CLIENT_ONLY_POST_SERVER_STARTUP_EVENT = "/event/server_startup"
ROUTE_CLIENT_ONLY_POST_SERVER_SHUTDOWN_EVENT = "/event/server_shutdown"


__all__ = [
    "ROUTE_POST_STATIC_BATCHING_COMPLETION",
    "ROUTE_POST_CONTINUOUS_BATCHING_COMPLETION",
    "ROUTE_POST_OPENAI_CHAT_COMPLETION",
    "ROUTE_GET_MODEL_ID",
    "ROUTE_CLIENT_ONLY_POST_SERVER_STARTUP_EVENT",
    "ROUTE_CLIENT_ONLY_POST_SERVER_SHUTDOWN_EVENT",
]
